config/routes.rb
Rails.application.routes.draw do

  resources :bands
  resources :concerts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    has_many :concerts, dependent: :destroy
    has_many :crews, dependent: :destroy 
    
    accepts_nested_attributes_for :crews

    enum band_type: %i[band girl_band boy_band]

    def number_of
        self.concerts.count
    end

    def total
        self.concerts.map{|concert| concert.assistants}.sum
    end

    def this_month
        self.concerts.where(date: (Date.today.beginning_of_month)..(Date.today)).count
    end

    def last_concert
        self.concerts.order(:date).last.date.strftime("%Y-%^B-%A") if self.concerts.any?
    end

    def max_assistants
        self.concerts.maximum(:assistants)
    end

    def longest
        self.concerts.map{|concert| concert.duration}.max
    end

end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :band


end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :band
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
    end

    def show
        @band = Band.find(params[:id])
        @concerts = @band.concerts
        @crews = @band.crews
    end

    def new
        @band = Band.new
        @band_types = Band.band_types.keys
        @crews = @band.crews.build
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to bands_path, notice: "El registro se ha agregado con éxito."
        else
            render :new
        end
    end

    def edit
        @band = Band.find(params[:id])
        @band_types = Band.band_types.keys
    end

    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to bands_path
        else
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy

        respond_to do |format|
            format.html { redirect_to bands_url, notice: "Band was successfully destroyed." }
        end
    end

    private

    def band_params
        params.require(:band).permit(:name, :members, :first_show, :band_type, crews_attributes:[:id, :name, :instrument, :_destroy])
    end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

    def index
        @concerts = Concert.all
    end

    def new
        @concert = Concert.new
        @bands = Band.all.pluck(:name, :id)
    end

    def create
        @concert = Concert.create(concert_params)

        if @concert.save
            redirect_to concerts_path, notice: "El registro se ha agregado con éxito."
        else
            render :new
        end
    end

    def edit
        @concert = Concert.find(params[:id])
        @bands = Band.all.pluck(:name, :id)
    end

    def update
        @concert = Concert.find(params[:id])

        if @concert.update(concert_params)
            redirect_to concerts_path
        else
            render :edit
        end
    end

    def destroy
        @concert = Concert.find(params[:id])
        @concert.destroy

        respond_to do |format|
            format.html { redirect_to concerts_url, notice: "El registro fue destruido." }
        end
    end

    private

    def concert_params
        params.require(:concert).permit(:date, :place, :assistants, :duration, :band_id)
    end

end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/_crew_fields.html.erb
<div class="nested-fields">
    <div class="form-group">
       <%= f.label "Nombre" %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label "Instrumento" %>
        <%= f.text_field :instrument, class: 'form-control' %>
    </div>
   <%= link_to_remove_association "Delete", f, class: 'd-flex justify-content-end' %>
</div>

app/views/bands/_form.html.erb
<%= form_with(model: band, local: true) do |form| %>
    <% if band.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved: </h2>
            <ul>
                <% band.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <%= form.label :Nombre %>
                <%= form.text_field :name, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label 'Cantidad de integrantes' %>
                <%= form.text_field :members, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label 'Fecha debut   ' %>
                <%= form.date_select :first_show, order: [:day, :month, :year], start_year: 1990, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label 'Tipo   ' %>
                <%= form.select :band_type, @band_types, class: 'form-control'%>
            </div>

            <h5><strong>Integrantes</strong></h5>

            <div class='form-group'>
                <%= form.fields_for :crews do |t| %>
                <%= render "crew_fields", :f => t %>
            <% end %>
      
                <div>
                    <br>
                    <%= link_to_add_association "Agregar integrante", form, :crews %> <!-- (*) -->
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <%= form.submit 'Guardar', class: 'btn btn-primary btn-block' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/bands/edit.html.erb
<div class="container my-5">
  <div class="col">
    <h3>Editar banda</h3>

    <%= render 'form', band: @band %>
  </div>
</div>

app/views/bands/index.html.erb
<div class='container my-3'>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Banda</th>
                <th scope="col">N° Integrantes</th>
                <th scope="col">Fecha debut</th>
                <th scope="col">Tipo</th>
                <th scope="col">Total conciertos</th>
                <th scope="col">Total asistentes</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody class='text-center'>
            <% @bands.each do |band| %>
            <tr>
                <td class='text-left'><%= link_to "#{band.name}", band_path(band)%></td>
                <td><%= band.members %></td>
                <td><%= band.first_show.strftime("%d-%m-%Y") %></td>
                <td><%= band.band_type %></td>
                <td><%= band.number_of %></td>
                <td><%= band.total %></td>
                <td><%= link_to 'Editar', edit_band_path(band) %></td>
                <td><%= link_to 'Eliminar', band, method: :delete, data: {confirm: "¿Está seguro de eliminar la información asociada a #{band.name}?"} %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <br>
</div>

app/views/bands/new.html.erb
<div class="container my-5">
  <div class="col">
    <h3>Nueva banda</h3>

    <%= render 'form', band: @band %>
  </div>
</div>

app/views/bands/show.html.erb
<div class='container'>
    <div class='row'>
        <div class='my-3  justify-content-center col-md-4'>
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title text-center"><strong><%= @band.name %></strong></h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong><%= "Integrantes:" %></strong></li>
                    <% @crews.each do |member|%>
                    <li class="list-group-item border-0"><%= "#{member.name} / #{member.instrument}" %></li>
                    <% end %>
                    <li class="list-group-item"><strong>Conciertos en este mes:</strong> <%=  @band.this_month %></li>
                    <li class="list-group-item"><strong>Último concierto: </strong><%=  @band.last_concert%></li>
                    <li class="list-group-item"><strong>Máximo de asistentes: </strong><%=  @band.max_assistants %></li>
                    <li class="list-group-item"><strong>Mayor duración de concierto: </strong><%= @band.longest %></li>  
                </ul>
            </div>
        </div>
        <div class='my-3 col-md-8'>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Fecha</th>
                        <th scope="col">Lugar</th>
                        <th scope="col">Asistentes</th>
                        <th scope="col">Duración (min)</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody class='text-center'>
                    <% @concerts.order(date: :desc).each do |concert| %>
                        <tr>
                            <td class='text-left'><%= concert.date.strftime("%d-%m-%Y")%></td>
                            <td><%= concert.place %></td>
                            <td><%= concert.assistants%></td>
                            <td><%= concert.duration %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
    <% if concert.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(band.errors.count, "error") %> prohibited this band from being saved: </h2>
            <ul>
                <% concert.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="row">
        <div class="col-md-6">

            <div class="form-group">
                <%= form.label 'Fecha:   ' %>
                <%= form.date_select :date, order: [:day, :month, :year], start_year: 1990, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :Lugar %>
                <%= form.text_field :place, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :Asistentes %>
                <%= form.text_field :assistants, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label 'Duración (min)' %>
                <%= form.text_field :duration, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label 'Banda:   ' %>
                <%= form.select :band_id, @bands, class: 'form-control'%>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <%= form.submit 'Guardar', class: 'btn btn-primary btn-block' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/concerts/edit.html.erb
<div class="container my-2">
  <div class="col">
    <h5> Editar Concierto</h5>

    <%= render 'form', concert: @concert %>
  </div>
</div>

app/views/concerts/index.html.erb
<div class='container my-2'>
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Lugar</th>
            <th scope="col">Asistentes</th>
            <th scope="col">Duración (min)</th>
            <th scope="col">Banda</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody class='text-center'>
        <% @concerts.order(date: :desc).each do |concert| %>
            <tr>
                <td class='text-left'><%= concert.date.strftime("%d-%m-%Y")%></td>
                <td><%= concert.place %></td>
                <td><%= concert.assistants%></td>
                <td><%= concert.duration %></td>
                <td><%= concert.band.name %></td>
                <td><%= link_to 'Editar', edit_concert_path(concert) %></td>
                <td><%= link_to 'Eliminar', concert, method: :delete, data: {confirm: "¿Está seguro de eliminar este registro?"} %></td>
            </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/concerts/new.html.erb
<div class="container my-2">
  <div class="col">
    <h5>Nuevo Concierto</h5>

    <%= render 'form', concert: @concert %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
          <ul class="navbar-nav  mr-auto">
            <li class="nav-item">
              <h5><strong>Productora de eventos DL</strong></h5>
            </li>
          </ul>
          <ul class='navbar-nav ml-auto'>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">Bandas</a>
                <div class="dropdown-menu">
                  <%= link_to 'Ver', bands_path, class: 'dropdown-item' %>
                  <%= link_to 'Crear', new_band_path, class: 'dropdown-item' %>
                </div>
              </li>
 
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">Conciertos</a>
                <div class="dropdown-menu">
                  <%= link_to 'Ver', concerts_path, class: 'dropdown-item' %>
                  <%= link_to 'Crear', new_concert_path, class: 'dropdown-item' %>
                </div>
              </li>
          </ul>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>